### ISSUE TITLE
Comments in requirements.txt

### ISSUE THREAD

**Issue by kb-** [tddschn/poetry-add-requirements.txt#1]
poetry-add-requirements.txt v1.1.1

Comment (lines beginning with #) are treated as requirement entries, which results in failure. https://pip.pypa.io/en/stable/reference/requirements-file-format/

requirements.txt:
panel
#datashader
holoviews

log:
  • panel

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
Running poetry add #datashader

'files'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
...

**Comment by tddschn** [comment]
Hey thanks for filing the issue!

I was aware of this and choose not to support many (or most) of the `requirement.txt` spec, because 
- I did not find an easy way to support them (I think `pip` itself only offers an [easy-to-use installation API](https://github.com/pypa/pip/blob/d0641740d5bdecf8c55729b2ff34ead8eff8e367/src/pip/_internal/req/req_install.py#L770), how the file is parse is internal to pip and undocumented). 
- I have limited time and only made what was needed for my use cases.

Please feel free to suggest ideas to support this, or open a PR. :)

**Comment by tddschn** [comment]
Please update the tool to v1.1.4 and try again. :)

**Comment by kb-** [comment]
The new version just ignores the # and therefore treats comments as modules to install.

I would do this:

utils.py
```
def preprocess_line(line: str) -> str:
    return line.split('#')[0].strip()  # Remove comments and leading/trailing whitespace
```

**Comment by tddschn** [comment]
@kb- Thanks for the suggestion. 

I just tested how pip 23.2.1 treats comments, and I think it ignores comment lines. 

Is there any source that supports this?
> The new version just ignores the # and therefore treats comments as modules to install

**Comment by tddschn** [comment]
I found the `requirements-parser` project also just ignore lines that start with '#', see https://sourcegraph.com/github.com/madpah/requirements-parser/-/blob/requirements/parser.py?L62=

I think I'm gonna do just that. :)
